#include "../src/action_detour_contract.h"
#include <stdio.h>
#include <sstream>
#include <vector>

using namespace mb::action_detour;
static int checks = 0, failures = 0;
static void check(bool ok, const char* name) {
    ++checks;
    if (!ok) { ++failures; fprintf(stderr, "FAIL: %s\n", name); }
}
static std::vector<uint8_t> hex(const char* text) {
    std::istringstream stream(text);
    std::vector<uint8_t> out;
    unsigned value;
    while (stream >> std::hex >> value) out.push_back((uint8_t)value);
    return out;
}
struct Fixture {
    Entry entry;
    uint64_t relayAddress, handlerAddress;
    std::vector<uint8_t> live, relay, trampoline, handler;
    Evidence evidence() const {
        Evidence e;
        e.coopEnabled = e.seamlessLoaded = true;
        e.imageBase = UINT64_C(0x7FF74FFF0000);
        e.seamlessBase = UINT64_C(0x180000000);
        e.relayAddress = relayAddress;
        e.handlerAddress = handlerAddress;
        e.live = {live.data(), live.size()};
        e.relay = {relay.data(), relay.size()};
        e.trampoline = {trampoline.data(), trampoline.size()};
        e.handler = {handler.data(), handler.size()};
        return e;
    }
    bool accepted() const { return matches(entry, evidence()); }
};

static void reject_changed_byte(Fixture f, std::vector<uint8_t> Fixture::*field,
                                size_t index, const char* name) {
    (f.*field)[index] ^= 1;
    check(!f.accepted(), name);
}

int main() {
    // Independent exact process capture, not generated by the validator:
    // work/elden-minecraft/coop/action-code-inspection.json, PID 33296.
    Fixture fixtures[] = {
        {Entry::ConsumePress, UINT64_C(0x7FF74FEE04D4), UINT64_C(0x7FF74FEF2250),
         hex("e9 2f b5 48 ff d2 74 61 0f b6 4a 20 f6 c1 04 74 58 41 80 b8 81 00 00 00 00"),
         hex("ff 25 00 00 00 00 50 22 ef 4f f7 7f 00 00"),
         hex("4c 8b c1 48 85 d2 ff 25 00 00 00 00 a6 4f a5 50 f7 7f 00 00"),
         hex("48 b8 b0 02 96 9e d9 01 00 00 66 48 0f 6e e8 49 bb f0 40 09 80 01 00 00 00 41 ff e3")},
        {Entry::GetMsg, UINT64_C(0x7FF74FEE0F61), UINT64_C(0x7FF74FEF0C30),
         hex("e9 1c 13 88 fd 44 3b 41 14 73 23 48 8b 41 08"),
         hex("ff 25 00 00 00 00 30 0c ef 4f f7 7f 00 00"),
         hex("3b 51 10 72 0e ff 25 00 00 00 00 6e fc 65 52 f7 7f 00 00 ff 25 00 00 00 00 45 fc 65 52 f7 7f 00 00"),
         hex("48 b8 20 03 94 9f d9 01 00 00 66 48 0f 6e e8 49 bb 70 5d 09 80 01 00 00 00 41 ff e3")}
    };
    for (const Fixture& f : fixtures) {
        check(f.accepted(), "captured cooperative detour accepted");
        auto e = f.evidence(); e.coopEnabled = false;
        check(!matches(f.entry, e), "solo refuses detour");
        e = f.evidence(); e.seamlessLoaded = false;
        check(!matches(f.entry, e), "missing ersc refuses detour");
        e = f.evidence(); e.seamlessBase += 0x1000;
        check(!matches(f.entry, e), "handler outside expected ersc RVA rejected");
        e = f.evidence(); e.imageBase += 0x1000;
        check(!matches(f.entry, e), "wrong main image base rejected");
        e = f.evidence(); e.imageBase = UINT64_MAX;
        check(!matches(f.entry, e), "image arithmetic overflow rejected");
        e = f.evidence(); e.relayAddress = 1;
        check(!matches(f.entry, e), "trampoline address underflow rejected");
        check(!matches(static_cast<Entry>(99), f.evidence()), "unknown entry rejected");
        // Each captured byte after the patched entry must remain unchanged.
        for (size_t i = 0; i < f.live.size(); ++i)
            reject_changed_byte(f, &Fixture::live, i, "entry jump, target or original tail changed");
        for (size_t i = 0; i < f.relay.size(); ++i)
            reject_changed_byte(f, &Fixture::relay, i, "relay opcode/displacement/target changed");
        // Covers original instructions, the inverse condition, taken target,
        // absolute jump encodings, and both fallthrough/return destinations.
        for (size_t i = 0; i < f.trampoline.size(); ++i)
            reject_changed_byte(f, &Fixture::trampoline, i, "trampoline code or control flow changed");
        for (size_t i = 0; i < f.handler.size(); ++i)
            if (i < 2 || i >= 10)
                reject_changed_byte(f, &Fixture::handler, i, "handler opcode or ersc target changed");
        Fixture zeroContext = f;
        memset(zeroContext.handler.data() + 2, 0, 8);
        check(!zeroContext.accepted(), "zero hook context rejected without dereference");
        Fixture differentContext = f;
        differentContext.handler[2] ^= 1;
        check(differentContext.accepted(), "opaque nonzero context is not dereferenced or address-pinned");
        for (Bytes Evidence::*field : {&Evidence::live, &Evidence::relay, &Evidence::trampoline, &Evidence::handler}) {
            e = f.evidence(); --(e.*field).size;
            check(!matches(f.entry, e), "truncated snapshot rejected");
            e = f.evidence(); (e.*field).data = nullptr;
            check(!matches(f.entry, e), "missing snapshot rejected");
        }
    }
    uint64_t target = 0;
    auto bytes = hex("e9 00 00 00 80");
    check(!relative_target(1, {bytes.data(), bytes.size()}, &target), "negative rel32 underflow rejected");
    bytes = hex("e9 ff ff ff 7f");
    check(!relative_target(UINT64_MAX - 8, {bytes.data(), bytes.size()}, &target), "positive rel32 overflow rejected");
    printf("action detour contract: %d checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
